# Exercícios Python e Numpy

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos na aula de Python e Numpy. Sabemos que acabamos passando meio rápido durante a aula, então o objetivo aqui é conseguir treinar os conceitos para você conseguir usa-los na prática mais tarde.

Qualquer dúvida pode ficar a vontade para perguntar no Slack ou diretamente para gente, vamos ficar felizes em ajudar :)

## Python

Aqui na parte de Python vamos passar por algumas das principais coisas que você precisa saber, é claro que não colocamos tudo de importante da linguagem, só o mais necessário.

### Variáveis

In [1]:
# Declare uma variavel chamada a e atribua o valor 10 a ela
a = 10

In [2]:
# Imprime essa variavel que você acabou de criar
a #print(a)

10

In [3]:
# Crie uma outra variavel b que recebe o valor de a so que como string
b = '%d' % a

In [4]:
# Combine sua variavel b a variavel abaixo para obter a string "Hello 10" em uma variavel d
c = "Hello "
d = c+b

In [5]:
# Imprima a variável d
d

'Hello 10'

### Strings

In [6]:
my_str = 'Insira uma frase aqui!'

In [7]:
# Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)
my_str.replace('!', '?', 1)

'Insira uma frase aqui?'

In [8]:
# Crie uma lista "my_words" com cada palavra a frase
my_words = my_str.split(' ')
my_words

['Insira', 'uma', 'frase', 'aqui!']

### Listas

In [9]:
lista = [1, 23, 31, 40, 56, 16]

In [10]:
# Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)
for el in lista:
    print(el)

1
23
31
40
56
16


In [11]:
# Faça um for que imprima o dobro de cada elemento da lista "lista" 
for el in lista:
    print(el*2)

2
46
62
80
112
32


In [12]:
# Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension
dobro = [el*2 for el in lista]
dobro

[2, 46, 62, 80, 112, 32]

In [13]:
# Crie uma nova lista chamada "pares"
# Faça um for que itere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
# Imprima a lista "pares"
pares = [el for el in lista if el%2 != 0 ]
pares

[1, 23, 31]

In [14]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [15]:
# Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())
[el for el in lista2 if type(el) == str]

['oi', 'top', 'python']

#### Indexando

In [16]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [17]:
# Selecione o ultimo elemento da lista
my_list[-1]

70

In [18]:
# Selecione do primeiro até o 4 elemento da lista
my_list[0:4]

[0, 10, 20, 30]

In [19]:
# Selecione do segundo elemento da lista até o quinto
my_list[1:5]

[10, 20, 30, 40]

In [20]:
# Selecione do primeiro elemento da lista até o penultimo
my_list[:-1]

[0, 10, 20, 30, 40, 50, 60]

### Dicionários

In [21]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [22]:
# Crie um dicionario que contenha a contagem de cada elemento do vetor
my_dict = {el:0 for el in lista}
for el in lista:
    my_dict[el] += 1
#...

In [23]:
print(my_dict)

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}


### Funções

In [24]:
# Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    return sum(lista)

In [25]:
soma_elementos([1, 2, 3, 4, 5])

15

In [26]:
soma_elementos([-1, 5, 7, -2])

9

In [27]:
# Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip
def produto_escalar(lista1, lista2):
    result = 0
    for a, b in zip(lista1, lista2):
        result += a*b
    return result

In [28]:
produto_escalar([1, 2, 3], [0, 4, 7])

29

In [29]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

391

In [30]:
# Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par
def par_ou_impar(n=20):
    for i in range(1, n+1):
        if i%2 == 0:
            print('%d Par' % i)
        else:
            print('%d Impar' % i)

In [31]:
par_ou_impar(4)

1 Impar
2 Par
3 Impar
4 Par


In [32]:
par_ou_impar(15)

1 Impar
2 Par
3 Impar
4 Par
5 Impar
6 Par
7 Impar
8 Par
9 Impar
10 Par
11 Impar
12 Par
13 Impar
14 Par
15 Impar


In [33]:
# Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)
def diga_indice(lista):
    for idx, val in enumerate(lista):
        print(idx, val)

In [34]:
diga_indice(['1', '2', '3'])

0 1
1 2
2 3


In [35]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

0 a
1 b
2 c
3 d
4 e


## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

In [36]:
# Importando a biblioteca
import numpy as np

### Arrays

In [37]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [38]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta
print(a.shape)
print(b.shape)
print(c.shape)

(7,)
(2, 4)
(3, 4)


In [39]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb
np.random.rand(20)

array([0.65847213, 0.55706772, 0.36897904, 0.44922503, 0.07439818,
       0.27012537, 0.74978885, 0.01886589, 0.01691932, 0.51514952,
       0.09322705, 0.40196567, 0.55511059, 0.7309397 , 0.2848414 ,
       0.74833361, 0.56048155, 0.13109792, 0.35329762, 0.24661168])

In [40]:
# Crie um array de uns com shape (4, 5)
np.zeros([4, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
np.ones([4, 2]) * 77

array([[77., 77.],
       [77., 77.],
       [77., 77.],
       [77., 77.]])

In [42]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]
np.arange(0, 101, 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Indexando

In [43]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[21  1 49 16 16 25 10 23  7 19 28 34 27 47  0]


In [44]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[4:10]

array([16, 25, 10, 23,  7, 19])

In [45]:
# Selecione todos os elementos maiores que 20
my_array[my_array > 20]

array([21, 49, 25, 23, 28, 34, 27, 47])

In [46]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [47]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix[0][2]

3

In [48]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix[0][-1]

4

In [49]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
my_matrix[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [50]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
my_matrix[0:2, -3:]

array([[2, 3, 4],
       [6, 7, 8]])

In [51]:
# Selecione os elementos da ultima coluna inteira
my_matrix[:, [-1]]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [52]:
# Selecione os elementos da 2a linha inteira
my_matrix[1]

array([5, 6, 7, 8])

### Operações

In [53]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[0 4 6 2 1]


In [54]:
# Some 10 a todos os elementos de my_array
my_array + 10

array([10, 14, 16, 12, 11])

In [55]:
# Multiplique todos os elementos de my_array por 4
my_array * 4

array([ 0, 16, 24,  8,  4])

In [56]:
# Obtenha a soma de todos os elementos de my_array
my_array.sum()

13

In [57]:
# Obtenha a média de todos os elementos de my_array
my_array.mean()

2.6

In [58]:
# Obtenha o indice do maior elemento de my_array
my_array.max()

6

In [59]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[6 8 0 7 1] 

[6 4 4 9 0]


In [60]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[8 1 3 6 0] 

[[0 8 0 7 4]
 [3 9 3 2 1]
 [6 0 1 5 5]
 [0 5 7 3 9]
 [3 5 1 4 9]
 [5 1 9 3 0]
 [9 3 8 2 7]
 [9 9 7 8 1]
 [1 4 0 9 8]
 [2 9 6 6 5]]


In [61]:
# Some my_array elemento por elemento em cada linha de my_other_array

In [62]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[3 9 0 2]
 [4 4 7 6]
 [4 2 8 6]
 [8 6 4 6]
 [4 3 1 1]] 

[[3 1 4 4 4]
 [2 2 5 3 0]
 [2 0 1 9 5]
 [4 8 3 4 3]
 [0 2 9 0 9]
 [4 9 4 6 1]
 [2 6 3 1 2]
 [0 1 0 3 0]
 [5 2 7 2 3]
 [5 7 6 9 6]]


In [63]:
# Faça a multiplicação entre my_other_array e my_array

In [64]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)

In [65]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[0 6 1 0]
 [2 5 4 7]
 [7 6 4 7]
 [5 8 5 9]
 [9 8 6 1]]


In [66]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)


In [67]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [68]:
# Gere a array anterior usando np.arange e a função reshape
a = np.arange(16)
a.reshape([2,-1])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])