<h1><center>
    Revisão de conteúdo para Ciência de Dados
</center></h1>
 
<h3><center>
Bruno Gomes Coelho 
<br> 
bruno.gomes.coelho@usp.br
</center></h3>

<h1><center>
Numpy
</center></h1>
 


###  Numpy I

- Visão Geral
- Básico de Arrays
- Manipulação das dimensões
- Iterar e repartir
- Indexação estilosa
- Cópias e visualizações

### Numpy

- Uma das grandes (numpy, scipy, matplotlib, ...) bibliotecas Python
- Matrizes multidimensionais (computação orientada a matriz)
- Majoritariamente escrito em C (eficiência)
- Projetado para computação científica (conveniência)

Import:
```python
import numpy as np
```

Numpy opera sobre 1 tipo básico: np.array 

Representa uma lista, semelhante a Python

In [1]:
import numpy as np   # Importando 

lst = [x for x in range(10)]
print("Python:", type(lst), lst)

np_lst = np.array(lst)
print("Numpy:", type(np_lst), np_lst)

Python: <class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy: <class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]


Também podemos criar matrizes

In [2]:
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Diferenças quanto a matrizes Python:

### Diferenças quanto a matrizes Python:
- **Grandes quantidades de dados numéricos**
    - muito mais eralmente muito mais eficientes que as listas

In [3]:
import random
size = int(10e4)
space = "\n\n"

In [4]:
%%time
# "mágica" do %%time
x = [random.random() for x in range(size)]
y = [x**2 for x in x]

CPU times: user 36.4 ms, sys: 4.04 ms, total: 40.4 ms
Wall time: 39.9 ms


In [5]:
%%time
# numpy version
# ...
x = np.random.rand(size)
y = x**2

CPU times: user 10.2 ms, sys: 0 ns, total: 10.2 ms
Wall time: 10.3 ms


### Diferenças quanto a matrizes Python:
- Grandes quantidades de dados numéricos
    - muito mais eralmente muito mais eficientes que as listas
- Mil e uma funcionalidades extras


### Criando arrays ou matrizes

- A partir de uma lista

In [6]:
print(np.array([1, 3, 5, 7, 9, 10]), space)

matrix = np.array([[1, 2, 3, 4, 5, 6],
                   [101, 102, 103, 104, 105, 106],
                   [201, 202, 203, 204, 205, 206]]
              )
print(matrix)

[ 1  3  5  7  9 10] 


[[  1   2   3   4   5   6]
 [101 102 103 104 105 106]
 [201 202 203 204 205 206]]


- Constantes

In [7]:
print(np.zeros(8))

print(np.ones(10), space)

# matriz
print(np.ones((3, 3)))

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- Sequências

In [8]:
print(np.arange(10))

print(np.linspace(1, 2, 5), space)

print(np.identity(3))

[0 1 2 3 4 5 6 7 8 9]
[1.   1.25 1.5  1.75 2.  ] 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Como saber de todas as funções do numpy?

- Google é seu amigo;
- Ver [documentação](https://docs.scipy.org/doc/numpy/)
- Prática

### Tipos
Numpy suporta diversos tipos;

Podemos acessar o tipo dos nossos dados com .dtype

In [9]:
# ...
matrix.dtype

dtype('int64')

Aproveitando, podemos mudar o tipo com .astype


In [10]:
temp = matrix.astype(float)

print(temp, space, temp.dtype)

[[  1.   2.   3.   4.   5.   6.]
 [101. 102. 103. 104. 105. 106.]
 [201. 202. 203. 204. 205. 206.]] 

 float64


![numpy_dtypes.png](attachment:numpy_dtypes.png)

### Indexação no numpy
- Cada dimensão de um array é chamada de eixo
- Os eixos são numerados a partir de 0
- Os elementos são acessados usando [] (semelhante a listas)



In [11]:
matrix = np.random.rand(2, 2)
print(matrix)

[[0.15649908 0.02838213]
 [0.30609809 0.04127061]]


In [12]:
print("0: ", matrix[0])
print("1: ", matrix[1])

0:  [0.15649908 0.02838213]
1:  [0.30609809 0.04127061]


### Repartindo arrays (slicing)
- Slicing semelhante a python mas em múltiplas dimensões
- Omitir dimensões significa o slice inteiro

In [13]:
print(matrix)

[[0.15649908 0.02838213]
 [0.30609809 0.04127061]]


In [14]:
# Formato da matrix
# ...
matrix

array([[0.15649908, 0.02838213],
       [0.30609809, 0.04127061]])

In [15]:
# Linha 1, todas as colunas
# ... 
matrix[0]

array([0.15649908, 0.02838213])

In [16]:
# Coluna 2, todas as linhas
# ...
matrix[:, 1]

array([0.02838213, 0.04127061])

```python
matrix[:, 2]
```

In [17]:
# Crie um array de uma dimenção (5, 5) com elementos inteiros aletórios entre 0 e 10
# ...
temp = np.random.rand(5, 5)

In [18]:
temp

array([[0.18339191, 0.23188711, 0.76600575, 0.13970682, 0.6483744 ],
       [0.82603527, 0.35933388, 0.8727005 , 0.22586329, 0.46959911],
       [0.44544066, 0.10464895, 0.51289479, 0.66005579, 0.59175391],
       [0.4979611 , 0.93577709, 0.53710247, 0.31251488, 0.74628593],
       [0.89442089, 0.02618527, 0.22914817, 0.79740441, 0.99728808]])

In [19]:
# Linhas 1 a 3, colunas 1 a 3
# ...
temp[1:4, 1:4]

array([[0.35933388, 0.8727005 , 0.22586329],
       [0.10464895, 0.51289479, 0.66005579],
       [0.93577709, 0.53710247, 0.31251488]])

Perceba que o 2 número não é inclusivo!

In [20]:
print(matrix, space)
# Linha 0, 2
# ... 

[[0.15649908 0.02838213]
 [0.30609809 0.04127061]] 




```python
matrix[[0, 2]]
```

In [21]:
print(matrix, space)

# Elemento 0,0 e 2,2
# ...
matrix[[0, 1]]

[[0.15649908 0.02838213]
 [0.30609809 0.04127061]] 




array([[0.15649908, 0.02838213],
       [0.30609809, 0.04127061]])

In [22]:
# Dúvidas?

### Boolean indexing

Podemos utilizar uma máscara de booleanos para indexar;

Apenas os True serão utilizados

In [23]:
# apenas os números pares
x = np.arange(1, 10)
# ...
index = None
print(x, space, index)

[1 2 3 4 5 6 7 8 9] 

 None


In [24]:
x[index]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
# And now for something completely different

matrix = np.array([[3, 4], [103, 104], [203, 204]])
# Verificar se os números da minha matriz pertencem a uma lista de números
elements = [3, 101, 105, 204, 1000]
# como?
# ...
matrix

array([[  3,   4],
       [103, 104],
       [203, 204]])

In [26]:
# python
answer = np.zeros(matrix.shape)

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        answer[i][j] = matrix[i][j] in elements
        
answer = answer.astype(bool)
answer

array([[ True, False],
       [False, False],
       [False,  True]])

```python
# python
answer = np.zeros(matrix.shape)

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        answer[i][j] = matrix[i][j] in elements
        
answer = answer.astype(bool)
answer
```

In [27]:
# numpy

Pesquisem as coisas :)

Manipulando formato

In [28]:
# Transposta
matrix.T

array([[  3, 103, 203],
       [  4, 104, 204]])

### Reshape
- Modifica o formato, sem alterar os dados
- Formato necessita ser compatível


In [29]:
x = np.arange(1, 13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
x.shape

(12,)

In [31]:
# Dividir em 2 linhas
# ...
x.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

```python
x.reshape(2, 6)
```

In [32]:
# Dividir em 3 linhas, sem saber colunas
# ...
x.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

```python
x.reshape(3, -1)
```

In [33]:
y = x.reshape(-1, 1)
print(y)
y.shape

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


(12, 1)

In [34]:
# necessário ser compatível
try:
    x.reshape(5, -1)
except ValueError as e:
    print(e)

cannot reshape array of size 12 into shape (5,newaxis)


### Visualizações
- Uma _visualização_ é criada ao slice um array
- Uma _visualização_ é uma **referência** a uma parte de um array
- Alterar _visualização_ altera o array original
- Se necessário, explicitamente faça cópia



In [35]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
y = x[:]
print(y, space)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 




In [37]:
print("Alterando 1 element")

y[-1, -1] = -1

print(x, space)
print(y)

Alterando 1 element
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 -1]] 


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 -1]]


In [38]:
z = np.copy(x[:])
z[0,0] = -1
print(x, space)
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 -1]] 


[[-1  2  3]
 [ 4  5  6]
 [ 7  8 -1]]


### Operação aritmétricas

Operações vetorizadas e extramamente eficientes

In [39]:
x = np.arange(6)
print(x, space)
y = x**2 
print(y)

[0 1 2 3 4 5] 


[ 0  1  4  9 16 25]


Diversas operações utilizam o conceito de **broadcasting**

Permitem que operamos com vetores de tamanhos diferentes

In [40]:
y = x**2 + 1
print(y)

[ 1  2  5 10 17 26]


In [41]:
# Produto par a par
print(x, space, y, space)
x*y

[0 1 2 3 4 5] 

 [ 1  2  5 10 17 26] 




array([  0,   2,  10,  30,  68, 130])

In [42]:
# Protudo escalar?
# ...
x*y

array([  0,   2,  10,  30,  68, 130])

In [43]:
x = np.ones((2, 2))
y = np.array([[1, 2], [3, 4]])

print(x, space, y)

[[1. 1.]
 [1. 1.]] 

 [[1 2]
 [3 4]]


In [44]:
# não é multiplicação de matriz!
x.dot(y)

array([[4., 6.],
       [4., 6.]])

In [45]:
x.dot(y)

array([[4., 6.],
       [4., 6.]])

Soma

In [46]:
# somar de todos os elementos
print(matrix, space)
matrix.sum()

[[  3   4]
 [103 104]
 [203 204]] 




621

In [47]:
# somar por linha
# ... 
matrix.sum(axis=1)

array([  7, 207, 407])

In [48]:
# somar por coluna
# ... 
matrix.sum(axis=0)

array([309, 312])

<center>
Dúvidas?
</center>
